services:
  client:
    build:
      context: .
      dockerfile: deployment/client.Dockerfile
    ports: ['5173:5173']
    volumes:
      - ./client:/app
  server:
    build:
      context: .
      dockerfile: deployment/server.Dockerfile
    ports: ['8000:8000']
    volumes:
      - ./server:/app
      - ./agents:/agents
