from server import database, models
db = database.SessionLocal()
user = db.query(models.User).filter(models.User.email == "admin@agencyos.com").first()
workspace = models.Workspace(name="Test Agency Alpha")
db.add(workspace)
db.commit()
member = models.WorkspaceMember(user_id=user.id, workspace_id=workspace.id, role="admin")
db.add(member)
db.commit()
print("Tenant access fixed")
