"""Add tenant_id to custom_agents and templates

Revision ID: 08f3fea755ba
Revises: 83e1d863cea9
Create Date: 2026-05-25 00:44:13.807884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f3fea755ba'
down_revision: Union[str, Sequence[str], None] = '83e1d863cea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_agents', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_custom_agents_tenant_id', 'workspaces', ['tenant_id'], ['id'])

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_templates_tenant_id', 'workspaces', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_templates_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('custom_agents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_custom_agents_tenant_id', type_='foreignkey')

    # ### end Alembic commands ###
