"""Update workflow_executions schema

Revision ID: 2314551a72e6
Revises: 22208c662996
Create Date: 2026-05-26 14:13:14.006983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2314551a72e6'
down_revision: Union[str, Sequence[str], None] = '22208c662996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pipeline_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('completed_nodes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('failed_nodes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('execution_context', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('retry_counts', sa.JSON(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('state_data')
        batch_op.drop_column('workflow_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('state_data', sqlite.JSON(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('retry_counts')
        batch_op.drop_column('execution_context')
        batch_op.drop_column('failed_nodes')
        batch_op.drop_column('completed_nodes')
        batch_op.drop_column('pipeline_id')

    # ### end Alembic commands ###
