import os
import glob

def fix_file(filepath):
    with open(filepath, 'r') as f:
        content = f.read()

    # 1. AsyncAsyncSession -> AsyncSession
    content = content.replace("AsyncAsyncSession", "AsyncSession")

    # 2. def invite_user -> async def invite_user
    content = content.replace("def invite_user(", "async def invite_user(")

    # 3. .filter(...) after execute -> execute(select(...).filter(...))
    # It looks like: (await db.execute(select(models.X))).filter(models.X.y == z)
    # We want: (await db.execute(select(models.X).filter(models.X.y == z)))
    
    # We can do this iteratively by finding `))).filter(` and moving the parenthesis.
    import re
    # Match: (await db.execute(select(...))).filter(...)
    # We replace `))).filter(` with `).filter(` and add `))` at the very end of the filter call? 
    # Or just replace `))).filter(` with `).filter(` and `.scalars()` with `)).scalars()`
    
    # Actually let's just do a string replacement for the exact bad patterns generated by the previous mode.
    content = content.replace("))).filter(", ").filter(")
    
    # Now the end of the query might look like: .scalars().all())) or .scalars().first()))
    # But wait, we want the `)` from `db.execute(` to close AFTER the `.filter(...)` but BEFORE `.scalars()`.
    # Let's just fix the end:
    content = content.replace(").scalars().all()", ")).scalars().all()")
    content = content.replace(").scalars().first()", ")).scalars().first()")
    
    # Fix any triple/quadruple parens that got created:
    content = content.replace("))).scalars()", ")).scalars()")
    content = content.replace(")))).scalars()", ")).scalars()")

    # Ensure `execute` is matched correctly:
    # `(await db.execute(select(models.Workspace))).scalars().all()`
    content = content.replace("(await db.execute(select(models.Workspace))).scalars().all()", "(await db.execute(select(models.Workspace))).scalars().all()")
    
    # Actually, it's safer to just do a regex replace over lines:
    
    lines = content.split('\n')
    for i, line in enumerate(lines):
        # bad pattern: `(await db.execute(select(...).filter(...).scalars().all()))`
        # change to `(await db.execute(select(...).filter(...))).scalars().all()`
        line = line.replace(".scalars().all()))", "))).scalars().all()")
        line = line.replace(".scalars().first()))", "))).scalars().first()")
        
        # fix the too-many parens
        line = line.replace(")))).scalars()", ")).scalars()")
        line = line.replace("))).scalars()", ")).scalars()")
        
        lines[i] = line
        
    content = "\n".join(lines)
    
    # One more thing: def some_function with await inside it need to be async
    
    with open(filepath, 'w') as f:
        f.write(content)

for f in glob.glob('server/routers/*.py'):
    fix_file(f)

print("Done")
